# Problem 1 
Use the Pima Indians Diabetes Database dataset. 

Tasks: 

●  Load the dataset using Pandas. 

●  Check missing values using isnull().sum(). 

●  Replace invalid 0 values in columns like Glucose, BloodPressure, and BMI with NaN. 

●  Apply: 

  ○  Necessary Imputation ( Must be done with the proper one ) 

●  Create a categorical column: 

   ○  Age_Group 

■   Young (<30) 
■   Adult (30–50) 
■   Senior (>50) 

●  Apply Encoding on Age_Group. Choose the proper encoding technique and explain why it is the 
best one

In [26]:
import pandas as pd
import numpy as np
df=pd.read_csv('diabetes.csv')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [27]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [28]:
#Replace invalid 0 values in columns like Glucose, BloodPressure, and BMI with NaN. 
columns_to_replace=['Glucose', 'BloodPressure', 'BMI']
for column in columns_to_replace:
     df[column]=df[column].replace(0,np.nan)
df.isnull().sum()

Pregnancies                  0
Glucose                      5
BloodPressure               35
SkinThickness                0
Insulin                      0
BMI                         11
DiabetesPedigreeFunction     0
Age                          0
Outcome                      0
dtype: int64

In [29]:
from sklearn.impute import SimpleImputer
imputer =SimpleImputer(strategy='mean')
df_imputed=imputer.fit_transform(df)
df_imputed=pd.DataFrame(df_imputed,columns=df.columns)
df_imputed.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [30]:
df_imputed

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,0.0,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,0.0,26.6,0.351,31.0,0.0
2,8.0,183.0,64.0,0.0,0.0,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,2.0,122.0,70.0,27.0,0.0,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,0.0,0.0,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,0.0,30.4,0.315,23.0,0.0

 Create a categorical column: 

 ○  Age_Group 

■   Young (<30) 

■   Adult (30–50)
 
■   Senior (>50)

In [31]:
def Age_Group(age):
    if age<30:
        return 'Young'
    elif age<50:
        return 'Adult'
    else:
        return 'Senior'
df_imputed['Age_Group']=df_imputed['Age'].apply(Age_Group)
df_imputed.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Age_Group
0,6.0,148.0,72.0,35.0,0.0,33.6,0.627,50.0,1.0,Senior
1,1.0,85.0,66.0,29.0,0.0,26.6,0.351,31.0,0.0,Adult
2,8.0,183.0,64.0,0.0,0.0,23.3,0.672,32.0,1.0,Adult
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0,Young
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0,Adult

In [32]:
#another way
df_imputed['Age_Group']=df_imputed['Age_Group'].apply(lambda x: 'Young' if x=='Young' else ('Adult' if x=='Adult' else 'Senior'))
df_imputed.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Age_Group
0,6.0,148.0,72.0,35.0,0.0,33.6,0.627,50.0,1.0,Senior
1,1.0,85.0,66.0,29.0,0.0,26.6,0.351,31.0,0.0,Adult
2,8.0,183.0,64.0,0.0,0.0,23.3,0.672,32.0,1.0,Adult
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0,Young
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0,Adult

In [33]:
 #Apply Encoding on Age_Group. Choose the proper encoding technique and explain why it is the best one
 #ordinalEncoder
from sklearn.preprocessing import OrdinalEncoder
encoder=OrdinalEncoder(categories=[['Senior','Adult','Young']])
df_imputed['Age_Group_Encoded']=encoder.fit_transform(df_imputed[['Age_Group']])
df_imputed.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Age_Group,Age_Group_Encoded
0,6.0,148.0,72.0,35.0,0.0,33.6,0.627,50.0,1.0,Senior,0.0
1,1.0,85.0,66.0,29.0,0.0,26.6,0.351,31.0,0.0,Adult,1.0
2,8.0,183.0,64.0,0.0,0.0,23.3,0.672,32.0,1.0,Adult,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0,Young,2.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0,Adult,1.0

In [34]:
#level encoding
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()
df_imputed['Age_Group_Label_Encoded']=label_encoder.fit_transform(df_imputed[['Age_Group']])
df_imputed.head()

c:\Users\user\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Age_Group,Age_Group_Encoded,Age_Group_Label_Encoded
0,6.0,148.0,72.0,35.0,0.0,33.6,0.627,50.0,1.0,Senior,0.0,1
1,1.0,85.0,66.0,29.0,0.0,26.6,0.351,31.0,0.0,Adult,1.0,0
2,8.0,183.0,64.0,0.0,0.0,23.3,0.672,32.0,1.0,Adult,1.0,0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0,Young,2.0,2
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0,Adult,1.0,0

In [35]:
print(df_imputed[
    ['Age_Group',
     'Age_Group_Encoded',
     'Age_Group_Label_Encoded']
].head())

  Age_Group  Age_Group_Encoded  Age_Group_Label_Encoded
0    Senior                0.0                        1
1     Adult                1.0                        0
2     Adult                1.0                        0
3     Young                2.0                        2
4     Adult                1.0                        0

# 2. 
Heart Disease Dataset – One Hot Encoding 

Dataset Link: 

Heart Disease UCI Dataset 

Use the Heart Disease UCI Dataset dataset. 

Tasks: 

●  Load the dataset. 

●  Identify categorical columns. 

●  Apply  Encoding on: 

○  cp (chest pain type) 

○  thal 

●  Compare dataframe shape before and after encoding.

In [36]:
#Load the dataset. 
df=pd.read_csv('heart.csv')
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [37]:
#●  Identify categorical columns. 
categorical_columns=df.select_dtypes(include=['object']).columns
print("Categorical columns:", categorical_columns)

Categorical columns: Index([], dtype='object')

In [38]:
#another way
print(df.dtypes)

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [39]:
#●  Apply  Encoding on: 

    #  ○  cp (chest pain type) 

    # ○  thal
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder=OneHotEncoder(sparse_output=False,drop='first')

#transform and transform the data
encoded_cp=one_hot_encoder.fit_transform(df[['cp']])

#print cp index
pd.DataFrame(encoded_cp,columns=one_hot_encoder.get_feature_names_out(['cp'])).head()

   cp_1  cp_2  cp_3
0   0.0   0.0   0.0
1   0.0   0.0   0.0
2   0.0   0.0   0.0
3   0.0   0.0   0.0
4   0.0   0.0   0.0

In [40]:
encoded_thal=one_hot_encoder.fit_transform(df[['thal']])

pd.DataFrame(encoded_thal,columns=one_hot_encoder.get_feature_names_out(['thal'])).head()

   thal_1  thal_2  thal_3
0     0.0     0.0     1.0
1     0.0     0.0     1.0
2     0.0     0.0     1.0
3     0.0     0.0     1.0
4     0.0     1.0     0.0

In [41]:
#●  Compare dataframe shape before and after encoding.
print("Original dataframe shape:", df.shape)
print("encoded_cp dataframe shape:", encoded_cp.shape)
print("encoded_thal dataframe shape:", encoded_thal.shape)

Original dataframe shape: (1025, 14)
encoded_cp dataframe shape: (1025, 3)
encoded_thal dataframe shape: (1025, 3)

3. Tips Dataset – Label Encoding 

Dataset Link: 

Seaborn Tips Dataset 

Use the Tips Dataset dataset. 

Tasks: 

●  Load dataset using Seaborn. 

●  Apply  Encoding on: 

      ○    sex 

      ○    smoker 

●  Create a new feature: 

      ○    tip_category 

           ■  Low (<3) 

           ■  Medium (3–6) 

           ■  High (>6) 

●  Encode tip_category.  

●  Choose the proper encoding technique and explain why it is the best one

In [42]:
import seaborn as sns
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [43]:
#Apply  Encoding on: 

      #1    sex ->ordinal encoding
from sklearn.preprocessing import OrdinalEncoder
original_encoder=OrdinalEncoder(categories=[['Male','Female']])

df['sex_encoded']=original_encoder.fit_transform(df[['sex']])

df['sex_encoded'].head()

0    1.0
1    0.0
2    0.0
3    0.0
4    1.0
Name: sex_encoded, dtype: float64

In [44]:
   #2    smoker 
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()
df['smoker_encoded']=label_encoder.fit_transform(df['smoker'])
df['smoker_encoded'].head()

0    0
1    0
2    0
3    0
4    0
Name: smoker_encoded, dtype: int64

create a new feature: 

      ○    tip_category 

           ■  Low (<3) 

           ■  Medium (3–6) 

           ■  High (>6) c

In [45]:
def tip_category (tips):
    if tips<3:
        return 'Low'
    elif tips<6:
        return 'Medium'
    else:
        return 'High'

df['tip_category']=df['tip'].apply(tip_category)

from sklearn.preprocessing import OrdinalEncoder
original_encoder=OrdinalEncoder(categories=[['Low','Medium','High']])

df['tip_category_encoded']=original_encoder.fit_transform(df[['tip_category']])

df['tip_category_encoded'].head()
#Choose the proper encoding technique and explain why it is the best one
# answer: Ordinal encoding is the best technique for encoding the 'tip_category' column because it has a natural order (Low < Medium < High). This allows the model to understand the relative ranking of the categories, which can be beneficial for certain algorithms that can leverage this information.

0    0.0
1    0.0
2    1.0
3    1.0
4    1.0
Name: tip_category_encoded, dtype: float64

4. Car Price Dataset – Train/Test Encoding Pipeline 

Dataset Link: 

Car Price Prediction Dataset 

Use the Car Price Prediction Dataset dataset. 

Tasks: 

●  Split the dataset into train and test sets first. 

●  Apply: 

  ○  Ordinal Encoding on fuel type (Petrol, Diesel, CNG) 
  
  ○  One Hot Encoding on transmission type 

●  Handle unknown categories in test data properly. 

●  Concatenate encoded columns with original dataframe. 

●  Drop original categorical columns.

In [46]:
df=pd.read_csv('CarPrice_Assignment.csv')
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [47]:
# Split the dataset into train and test sets first. 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder

X_train, X_test, y_train, y_test = train_test_split(df.drop('price', axis=1), df['price'], test_size=0.2, random_state=42)

#Apply: 

  #○  Ordinal Encoding on fuel type (Petrol, Diesel, CNG) 

ordinal_encoder = OrdinalEncoder(categories=[['gas', 'diesel', 'cng']])

X_train['fuel_type_encoded']=ordinal_encoder.fit_transform(X_train[['fueltype']])
X_train[['fueltype','fuel_type_encoded']].head()

    fueltype  fuel_type_encoded
66    diesel                1.0
111      gas                0.0
153      gas                0.0
96       gas                0.0
38       gas                0.0

In [48]:
 #○  One Hot Encoding on transmission type (1nd time more practice in morning)
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder
import pandas as pd
onehot_encoder=OneHotEncoder(sparse_output=False).set_output(transform='pandas')

#Handle unknown categories in test data properly.
encoded_train=onehot_encoder.fit_transform(X_train[['drivewheel']])
X_train=pd.concat([X_train,encoded_train],axis=1)

encoded_test=onehot_encoder.fit_transform(X_test[['drivewheel']])

# Concatenate encoded columns with original dataframe. 
X_test=pd.concat([X_test,encoded_test],axis=1)
print(X_train.head())


# Drop original categorical columns.
df.drop(['fueltype','drivewheel'],axis=1,inplace=True)
df.head()

     car_ID  symboling                CarName fueltype aspiration doornumber  \
66       67          0          mazda rx-7 gs   diesel        std       four
111     112          0            peugeot 504      gas        std       four
153     154          0  toyota corona hardtop      gas        std       four
96       97          1           nissan latio      gas        std       four
38       39          0       honda civic 1300      gas        std        two

       carbody drivewheel enginelocation  wheelbase  ...  stroke  \
66       sedan        rwd          front      104.9  ...    3.64
111      sedan        rwd          front      107.9  ...    2.19
153      wagon        fwd          front       95.7  ...    3.03
96       sedan        fwd          front       94.5  ...    3.29
38   hatchback        fwd          front       96.5  ...    3.58

     compressionratio  horsepower  peakrpm citympg highwaympg  \
66               22.0          72     4200      31         39
111               8.4          95     5000      19         24
153               9.0          62     4800      31         37
96                9.4          69     5200      31         37
38                9.0          86     5800      27         33

     fuel_type_encoded drivewheel_4wd  drivewheel_fwd  drivewheel_rwd
66                 1.0            0.0             0.0             1.0
111                0.0            0.0             0.0             1.0
153                0.0            0.0             1.0             0.0
96                 0.0            0.0             1.0             0.0
38                 0.0            0.0             1.0             0.0

[5 rows x 29 columns]

,car_ID,symboling,CarName,aspiration,doornumber,carbody,enginelocation,wheelbase,carlength,carwidth,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,std,two,convertible,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,std,two,convertible,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,std,two,hatchback,front,94.5,171.2,65.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,std,four,sedan,front,99.8,176.6,66.2,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,std,four,sedan,front,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

# 5. Heart Disease Dataset  

Dataset Link: 

Heart Disease UCI Dataset 

Use the Heart Disease UCI Dataset dataset. 

Tasks: 

●  Do preprocessing that  includes: 

    ○  Missing value imputation 

    ○  Outlier detection using IQR 

    ○  One Hot Encoding 

    ○  Ordinal Encoding 

●  Use ColumnTransformer 

●  Transform both training and testing datasets properly. 

●  Display final transformed feature matrix shape

In [49]:
df1=pd.read_csv('diabetes.csv')

df1.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

# 6. Diabetes Dataset – Compare Encoding Techniques 

Dataset Link: 

Pima Indians Diabetes Dataset 

Use the Pima Indians Diabetes Database dataset. 

Tasks: 

●  Create a categorical feature from BMI: 

      ○  Underweight 

      ○  Normal 
    
      ○  Overweight 

      ○  Obese 

●  Apply: 

      ○  Label Encoding 

      ○  Ordinal Encoding 

      ○  One Hot Encoding 

●  Write a short conclusion on which encoding is best for this feature.

In [50]:
df=pd.read_csv('diabetes.csv')
df
def find_weight(BMI):
    if BMI <18.5:
        return 'Underweight'
    elif BMI<18.5:
        return 'Normal'
    elif BMI<25:
        return 'Overweight'
    else:
        return 'Obese'

df['health']=df['BMI'].apply(find_weight)
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,health
0,6,148,72,35,0,33.6,0.627,50,1,Obese
1,1,85,66,29,0,26.6,0.351,31,0,Obese
2,8,183,64,0,0,23.3,0.672,32,1,Overweight
3,1,89,66,23,94,28.1,0.167,21,0,Obese
4,0,137,40,35,168,43.1,2.288,33,1,Obese
...,...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0,Obese
764,2,122,70,27,0,36.8,0.340,27,0,Obese
765,5,121,72,23,112,26.2,0.245,30,0,Obese
766,1,126,60,0,0,30.1,0.349,47,1,Obese
767,1,93,70,31,0,30.4,0.315,23,0,Obese

In [51]:
#  Label Encoding 
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()
df['health_encoded']=label_encoder.fit_transform(df['health'])
df['health_encoded']

0      0
1      0
2      1
3      0
4      0
      ..
763    0
764    0
765    0
766    0
767    0
Name: health_encoded, Length: 768, dtype: int64

In [ ]:
#Ordinal Encoding 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
X_train, X_test, y_train, y_test = train_test_split(df.drop('health', axis=1), df['health'], test_size=0.2, random_state=42)
ordinal_encoder = OrdinalEncoder(categories=[['Underweight', 'Normal', 'Overweight','Obese']])

y_train_encoded = ordinal_encoder.fit_transform(y_train.to_frame())

print(pd.DataFrame({'health': y_train, 'health_encoded': y_train_encoded.flatten()}).head())

          health  health_encoded
60   Underweight             0.0
618        Obese             3.0
346        Obese             3.0
294   Overweight             2.0
231        Obese             3.0

In [54]:
#One Hot Encoding 
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder=OneHotEncoder(sparse_output=False,drop='first')
encoded_health=one_hot_encoder.fit_transform(df[['health']])
encoded_health_df=pd.DataFrame(encoded_health,columns=one_hot_encoder.get_feature_names_out(['health']))
encoded_health_df.head()

   health_Overweight  health_Underweight
0                0.0                 0.0
1                0.0                 0.0
2                1.0                 0.0
3                0.0                 0.0
4                0.0                 0.0

# 7. Hotel Booking Dataset – High Cardinality Encoding 

Dataset Link: 

Hotel Booking Demand Dataset 

Use the Hotel Booking Demand Dataset dataset. 

Tasks: 

●  Load dataset. 

●  Apply: 

  ○  One Hot Encoding on hotel 

  ○  Label Encoding on booking status column

In [55]:
df=pd.read_csv('hotel_bookings.csv')
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [56]:
#One Hot Encoding on hotel
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder=OneHotEncoder(sparse_output=False,drop='first')
encoded_hotel=one_hot_encoder.fit_transform(df[['hotel']])
encoded_hotel_df=pd.DataFrame(encoded_hotel,columns=one_hot_encoder.get_feature_names_out(['hotel']))
encoded_hotel_df.head()

   hotel_Resort Hotel
0                 1.0
1                 1.0
2                 1.0
3                 1.0
4                 1.0

In [58]:
#Label Encoding on booking status column
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()
df['booking_status_encoded']=label_encoder.fit_transform(df['reservation_status'])
df[['reservation_status','booking_status_encoded']].head()

  reservation_status  booking_status_encoded
0          Check-Out                       1
1          Check-Out                       1
2          Check-Out                       1
3          Check-Out                       1
4          Check-Out                       1

# 8. Employee Attrition Dataset – Advanced Encoding Challenge 

Dataset Link: 

IBM HR Analytics Employee Attrition Dataset 

Use the IBM HR Analytics Employee Attrition Dataset dataset. 

Tasks: 

●  Split the dataset into train and test sets. 

●  Detects all categorical columns automatically. 

●  Apply: 

       ○  Ordinal Encoding for education level 

       ○  One Hot Encoding for department 

       ○  Label Encoding for target column 
●  Handle unseen categories in test data.

●  Create a reusable preprocessing function. ( Optional )  

●  Display transformed train and test datasets

In [59]:
df=pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [ ]:
from sklearn.model_selection import train_test_split
X=df.drop('Attrition', axis=1)
y=df['Attrition']

X_train, X_test, y_train, y_test = train_test_split(df.drop('Attrition', axis=1), df['Attrition'], test_size=0.2, random_state=42)

#Detects all categorical columns automatically.
categorical_columns=X_train.select_dtypes(include=['object']).columns
print("Categorical columns:", categorical_columns)

Categorical columns: Index(['BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole',
       'MaritalStatus', 'Over18', 'OverTime'],
      dtype='object')

In [64]:
# Ordinal Encoding for education level 
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder=OrdinalEncoder(categories=[['1','2','3','4','5']])
X_train['Education_Level_Encoded']=ordinal_encoder.fit_transform(X_train[['Education']])
X_train['Education_Level_Encoded']

1097    1.0
727     1.0
254     1.0
1175    2.0
1341    2.0
       ...
1130    2.0
1294    2.0
860     3.0
1459    1.0
1126    2.0
Name: Education_Level_Encoded, Length: 1176, dtype: float64

In [66]:
#One Hot Encoding for department 
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder=OneHotEncoder(sparse_output=False,drop='first')
encoded_department=one_hot_encoder.fit_transform(X_train[['Department']])
encoded_department_df=pd.DataFrame(encoded_department,columns=one_hot_encoder.get_feature_names_out(['Department']))
encoded_department_df

      Department_Research & Development  Department_Sales
0                                   1.0               0.0
1                                   1.0               0.0
2                                   0.0               1.0
3                                   1.0               0.0
4                                   1.0               0.0
...                                 ...               ...
1171                                1.0               0.0
1172                                1.0               0.0
1173                                1.0               0.0
1174                                1.0               0.0
1175                                0.0               1.0

[1176 rows x 2 columns]

In [70]:
#Label Encoding for target column 
label_encoder=LabelEncoder()
y_train_encoded=label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

X_train_transformed = X_train.copy()
X_test_transformed = X_test.copy()

print("--- Transformed Train Dataset ---")
display(X_train_transformed.head())


print("\n--- Transformed Test Dataset ---")
display(X_test_transformed.head())

--- Transformed Train Dataset ---

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Education_Level_Encoded
1097,24,Travel_Rarely,350,Research & Development,21,2,Technical Degree,1,1551,3,...,80,3,2,3,3,1,1,0,0,1.0
727,18,Non-Travel,287,Research & Development,5,2,Life Sciences,1,1012,2,...,80,0,0,2,3,0,0,0,0,1.0
254,29,Travel_Rarely,1247,Sales,20,2,Marketing,1,349,4,...,80,1,10,2,3,3,2,0,2,1.0
1175,39,Travel_Rarely,492,Research & Development,12,3,Medical,1,1654,4,...,80,0,7,3,3,5,4,1,0,2.0
1341,31,Travel_Rarely,311,Research & Development,20,3,Life Sciences,1,1881,2,...,80,1,10,2,3,10,8,0,2,2.0

--- Transformed Test Dataset ---

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1041,28,Travel_Rarely,866,Sales,5,3,Medical,1,1469,4,...,4,80,0,6,4,3,5,4,1,3
184,53,Travel_Rarely,1084,Research & Development,13,2,Medical,1,250,4,...,3,80,2,5,3,3,4,2,1,3
1222,24,Travel_Rarely,240,Human Resources,22,1,Human Resources,1,1714,4,...,3,80,1,1,2,3,1,0,0,0
67,45,Travel_Rarely,1339,Research & Development,7,3,Life Sciences,1,86,2,...,3,80,1,25,2,3,1,0,0,0
220,36,Travel_Rarely,1396,Research & Development,5,2,Life Sciences,1,304,4,...,4,80,0,16,3,4,13,11,3,7